apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
  type: ClusterIP




